"""
bootstrap_data.py

RESPONSIBILITY: Synthetic starter dataset for cold-start users.
200 examples covering all 6 categories.
Used when user has < MIN_TRAINING_SAMPLES corrected transactions.
"""


def get_bootstrap_data():
    """
    Returns (features, labels) tuple.
    features: list of feature strings (title + merchant + intent + entity)
    labels: list of category strings
    """
    data = [
        # ─── Food (40 examples) ─────────────────────────────────────────
        ("zomato food order", "zomato", "food_order", "restaurant", "Food"),
        ("swiggy delivery", "swiggy", "food_order", "restaurant", "Food"),
        ("dominos pizza order", "dominos", "food_order", "restaurant", "Food"),
        ("kfc bucket meal", "kfc", "food_order", "restaurant", "Food"),
        ("mcdonalds burger", "mcdonalds", "food_order", "restaurant", "Food"),
        ("starbucks coffee", "starbucks", "food_order", "restaurant", "Food"),
        ("subway sandwich", "subway", "food_order", "restaurant", "Food"),
        ("haldirams sweets", "haldirams", "food_order", "restaurant", "Food"),
        ("pizza hut delivery", "pizza_hut", "food_order", "restaurant", "Food"),
        ("burger king whopper", "burger_king", "food_order", "restaurant", "Food"),
        ("biryani restaurant order", "", "food_order", "restaurant", "Food"),
        ("canteen lunch payment", "", "generic_expense", "unknown", "Food"),
        ("mess food monthly", "", "generic_expense", "unknown", "Food"),
        ("cafe coffee day latte", "", "food_order", "restaurant", "Food"),
        ("dhaba dinner", "", "food_order", "restaurant", "Food"),
        ("bakery cake pastry", "", "food_order", "unknown", "Food"),
        ("tiffin service monthly", "", "generic_expense", "unknown", "Food"),
        ("thali meal restaurant", "", "food_order", "restaurant", "Food"),
        ("noodles chinese food", "", "food_order", "restaurant", "Food"),
        ("chai tea stall", "", "generic_expense", "unknown", "Food"),
        ("barbeque nation dinner", "", "food_order", "restaurant", "Food"),
        ("ice cream parlour", "", "food_order", "unknown", "Food"),
        ("dine in restaurant bill", "", "food_order", "restaurant", "Food"),
        ("takeaway food order", "", "food_order", "unknown", "Food"),
        ("grocery vegetables fruits", "", "generic_expense", "unknown", "Food"),
        ("juice shop fresh", "", "generic_expense", "unknown", "Food"),
        ("milk dairy daily", "", "generic_expense", "unknown", "Food"),
        ("paneer tikka restaurant", "", "food_order", "restaurant", "Food"),
        ("chicken roll street food", "", "food_order", "unknown", "Food"),
        ("momos food stall", "", "food_order", "unknown", "Food"),
        ("samosa chaat snacks", "", "generic_expense", "unknown", "Food"),
        ("sweet shop mithai", "", "generic_expense", "unknown", "Food"),
        ("maggi instant noodles", "", "generic_expense", "unknown", "Food"),
        ("fruits market vegetables", "", "generic_expense", "unknown", "Food"),
        ("breakfast dosa idli", "", "food_order", "restaurant", "Food"),
        ("lunch combo meal", "", "food_order", "restaurant", "Food"),
        ("dinner buffet restaurant", "", "food_order", "restaurant", "Food"),
        ("snacks evening tea", "", "generic_expense", "unknown", "Food"),
        ("swiggy instamart groceries", "swiggy", "generic_expense", "restaurant", "Food"),
        ("zepto vegetables delivery", "zepto", "generic_expense", "ecommerce", "Food"),

        # ─── Travel (35 examples) ───────────────────────────────────────
        ("uber ride cab", "uber", "travel_booking", "transport", "Travel"),
        ("ola auto ride", "ola", "travel_booking", "transport", "Travel"),
        ("rapido bike taxi", "rapido", "travel_booking", "transport", "Travel"),
        ("metro card recharge", "", "travel_booking", "transport", "Travel"),
        ("bus ticket booking", "", "travel_booking", "transport", "Travel"),
        ("irctc train ticket", "irctc", "travel_booking", "transport", "Travel"),
        ("makemytrip flight", "makemytrip", "travel_booking", "transport", "Travel"),
        ("redbus booking", "redbus", "travel_booking", "transport", "Travel"),
        ("indigo flight ticket", "indigo", "travel_booking", "transport", "Travel"),
        ("spicejet air fare", "spicejet", "travel_booking", "transport", "Travel"),
        ("petrol fuel station", "", "generic_expense", "unknown", "Travel"),
        ("diesel fuel pump", "", "generic_expense", "unknown", "Travel"),
        ("toll highway payment", "", "generic_expense", "unknown", "Travel"),
        ("parking lot charge", "", "generic_expense", "unknown", "Travel"),
        ("auto rickshaw fare", "", "travel_booking", "transport", "Travel"),
        ("cab ride airport", "", "travel_booking", "transport", "Travel"),
        ("train platform ticket", "", "travel_booking", "transport", "Travel"),
        ("flight booking airfare", "", "travel_booking", "transport", "Travel"),
        ("hotel accommodation stay", "", "travel_booking", "unknown", "Travel"),
        ("goibibo hotel booking", "goibibo", "travel_booking", "transport", "Travel"),
        ("cleartrip flight", "cleartrip", "travel_booking", "transport", "Travel"),
        ("yatra travel package", "yatra", "travel_booking", "transport", "Travel"),
        ("mobus ticket fare", "mobus", "travel_booking", "transport", "Travel"),
        ("capital region urban transport", "crut", "travel_booking", "transport", "Travel"),
        ("fastag highway toll", "", "generic_expense", "unknown", "Travel"),
        ("bike servicing fuel", "", "generic_expense", "unknown", "Travel"),
        ("cng gas refill auto", "", "generic_expense", "unknown", "Travel"),
        ("taxi airport transfer", "", "travel_booking", "transport", "Travel"),
        ("local train pass", "", "travel_booking", "transport", "Travel"),
        ("bus pass monthly", "", "travel_booking", "transport", "Travel"),
        ("road trip expense", "", "travel_booking", "unknown", "Travel"),
        ("cab pool sharing ride", "", "travel_booking", "transport", "Travel"),
        ("ferry boat ticket", "", "travel_booking", "transport", "Travel"),
        ("luggage transport delivery", "", "generic_expense", "unknown", "Travel"),
        ("bike rental scooter", "", "travel_booking", "transport", "Travel"),

        # ─── Entertainment (30 examples) ────────────────────────────────
        ("netflix subscription monthly", "netflix", "subscription", "subscription", "Entertainment"),
        ("spotify premium music", "spotify", "subscription", "subscription", "Entertainment"),
        ("hotstar plan annual", "hotstar", "subscription", "subscription", "Entertainment"),
        ("disney plus subscription", "disney_hotstar", "subscription", "subscription", "Entertainment"),
        ("prime video membership", "prime_video", "subscription", "subscription", "Entertainment"),
        ("youtube premium plan", "youtube", "subscription", "subscription", "Entertainment"),
        ("bookmyshow movie ticket", "bookmyshow", "generic_expense", "subscription", "Entertainment"),
        ("steam game purchase", "steam", "generic_expense", "subscription", "Entertainment"),
        ("jiocinema plan subscription", "jiocinema", "subscription", "subscription", "Entertainment"),
        ("zee5 annual plan", "zee5", "subscription", "subscription", "Entertainment"),
        ("movie theatre cinema hall", "", "generic_expense", "unknown", "Entertainment"),
        ("concert live show ticket", "", "generic_expense", "unknown", "Entertainment"),
        ("event festival pass", "", "generic_expense", "unknown", "Entertainment"),
        ("gaming online purchase", "", "generic_expense", "unknown", "Entertainment"),
        ("amusement park entry", "", "generic_expense", "unknown", "Entertainment"),
        ("sports match ticket", "", "generic_expense", "unknown", "Entertainment"),
        ("bowling alley fun", "", "generic_expense", "unknown", "Entertainment"),
        ("escape room activity", "", "generic_expense", "unknown", "Entertainment"),
        ("theme park rides", "", "generic_expense", "unknown", "Entertainment"),
        ("museum exhibition entry", "", "generic_expense", "unknown", "Entertainment"),
        ("comedy show standup", "", "generic_expense", "unknown", "Entertainment"),
        ("play drama theatre", "", "generic_expense", "unknown", "Entertainment"),
        ("music concert festival", "", "generic_expense", "unknown", "Entertainment"),
        ("vr gaming experience", "", "generic_expense", "unknown", "Entertainment"),
        ("ps5 game playstation", "", "generic_expense", "unknown", "Entertainment"),
        ("xbox game pass", "", "subscription", "subscription", "Entertainment"),
        ("apple music subscription", "", "subscription", "subscription", "Entertainment"),
        ("twitch prime gaming", "", "subscription", "subscription", "Entertainment"),
        ("sonyliv plan", "sonyliv", "subscription", "subscription", "Entertainment"),
        ("crunchyroll anime subscription", "crunchyroll", "subscription", "subscription", "Entertainment"),

        # ─── Utilities (40 examples) ────────────────────────────────────
        ("amazon shopping order", "amazon", "generic_expense", "ecommerce", "Utilities"),
        ("flipkart purchase", "flipkart", "generic_expense", "ecommerce", "Utilities"),
        ("myntra fashion clothing", "myntra", "generic_expense", "ecommerce", "Utilities"),
        ("meesho order delivery", "meesho", "generic_expense", "ecommerce", "Utilities"),
        ("jio recharge prepaid", "jio", "recharge", "utility_provider", "Utilities"),
        ("airtel postpaid bill", "airtel", "bill_payment", "utility_provider", "Utilities"),
        ("bsnl broadband monthly", "bsnl", "bill_payment", "utility_provider", "Utilities"),
        ("electricity bill payment", "", "bill_payment", "unknown", "Utilities"),
        ("wifi internet broadband", "", "bill_payment", "unknown", "Utilities"),
        ("water bill monthly", "", "bill_payment", "unknown", "Utilities"),
        ("rent payment monthly", "", "generic_expense", "unknown", "Utilities"),
        ("hostel fees accommodation", "", "generic_expense", "unknown", "Utilities"),
        ("emi loan installment", "", "generic_expense", "unknown", "Utilities"),
        ("credit card bill payment", "", "bill_payment", "unknown", "Utilities"),
        ("insurance premium health", "", "generic_expense", "unknown", "Utilities"),
        ("hospital medical bill", "", "generic_expense", "unknown", "Utilities"),
        ("pharmacy medicine purchase", "", "generic_expense", "unknown", "Utilities"),
        ("doctor consultation fees", "", "generic_expense", "unknown", "Utilities"),
        ("gas cylinder delivery", "", "generic_expense", "unknown", "Utilities"),
        ("society maintenance charge", "", "bill_payment", "unknown", "Utilities"),
        ("school tuition fees", "", "generic_expense", "unknown", "Utilities"),
        ("college semester fees", "", "generic_expense", "unknown", "Utilities"),
        ("nykaa beauty cosmetics", "nykaa", "generic_expense", "ecommerce", "Utilities"),
        ("ajio fashion purchase", "ajio", "generic_expense", "ecommerce", "Utilities"),
        ("bigbasket grocery order", "bigbasket", "generic_expense", "ecommerce", "Utilities"),
        ("blinkit quick delivery", "blinkit", "generic_expense", "ecommerce", "Utilities"),
        ("dmart shopping groceries", "dmart", "generic_expense", "ecommerce", "Utilities"),
        ("amazon pay recharge", "amazon", "recharge", "ecommerce", "Utilities"),
        ("vodafone recharge prepaid", "vodafone", "recharge", "utility_provider", "Utilities"),
        ("laundry dry cleaning", "", "generic_expense", "unknown", "Utilities"),
        ("salon haircut grooming", "", "generic_expense", "unknown", "Utilities"),
        ("tailor clothing alteration", "", "generic_expense", "unknown", "Utilities"),
        ("newspaper magazine subscription", "", "generic_expense", "unknown", "Utilities"),
        ("stationery office supplies", "", "generic_expense", "unknown", "Utilities"),
        ("laptop accessories purchase", "", "generic_expense", "unknown", "Utilities"),
        ("mobile phone charger", "", "generic_expense", "unknown", "Utilities"),
        ("furniture home appliance", "", "generic_expense", "unknown", "Utilities"),
        ("plumber electrician repair", "", "generic_expense", "unknown", "Utilities"),
        ("pest control service", "", "generic_expense", "unknown", "Utilities"),
        ("snapdeal order purchase", "snapdeal", "generic_expense", "ecommerce", "Utilities"),

        # ─── Income (30 examples) ───────────────────────────────────────
        ("salary credited monthly", "", "salary", "unknown", "Income"),
        ("freelance payment received", "", "generic_expense", "person", "Income"),
        ("cashback reward credited", "", "cashback", "unknown", "Income"),
        ("stipend scholarship monthly", "", "salary", "unknown", "Income"),
        ("bonus annual performance", "", "salary", "unknown", "Income"),
        ("dividend interest earned", "", "generic_expense", "unknown", "Income"),
        ("prize money won", "", "generic_expense", "unknown", "Income"),
        ("payment received from client", "", "generic_expense", "person", "Income"),
        ("papa sent money", "papa", "person_transfer", "person", "Income"),
        ("mom transferred amount", "mom", "person_transfer", "person", "Income"),
        ("friend paid back", "friend", "person_transfer", "person", "Income"),
        ("roommate rent share", "roommate", "person_transfer", "person", "Income"),
        ("brother gift money", "brother", "person_transfer", "person", "Income"),
        ("uncle birthday gift", "uncle", "person_transfer", "person", "Income"),
        ("interest bank account", "", "generic_expense", "unknown", "Income"),
        ("fixed deposit maturity", "", "generic_expense", "unknown", "Income"),
        ("mutual fund redemption", "", "generic_expense", "unknown", "Income"),
        ("tax refund government", "", "refund", "unknown", "Income"),
        ("deposit received rental", "", "generic_expense", "unknown", "Income"),
        ("allowance pocket money", "", "person_transfer", "person", "Income"),
        ("part time job payment", "", "salary", "unknown", "Income"),
        ("internship stipend monthly", "", "salary", "unknown", "Income"),
        ("tutoring income teaching", "", "salary", "unknown", "Income"),
        ("selling old items income", "", "generic_expense", "unknown", "Income"),
        ("commission earned sales", "", "generic_expense", "unknown", "Income"),
        ("royalty payment received", "", "generic_expense", "unknown", "Income"),
        ("loan repayment received", "", "generic_expense", "person", "Income"),
        ("insurance claim amount", "", "generic_expense", "unknown", "Income"),
        ("pension monthly credit", "", "salary", "unknown", "Income"),
        ("payroll direct deposit", "", "salary", "unknown", "Income"),

        # ─── Others (25 examples) ──────────────────────────────────────
        ("miscellaneous expense", "", "generic_expense", "unknown", "Others"),
        ("random payment shop", "", "generic_expense", "unknown", "Others"),
        ("unknown merchant payment", "", "generic_expense", "unknown", "Others"),
        ("cash withdrawal atm", "", "generic_expense", "unknown", "Others"),
        ("personal purchase general", "", "generic_expense", "unknown", "Others"),
        ("donation charity contribution", "", "generic_expense", "unknown", "Others"),
        ("gift present someone", "", "generic_expense", "unknown", "Others"),
        ("fine penalty payment", "", "generic_expense", "unknown", "Others"),
        ("fees charges bank", "", "generic_expense", "unknown", "Others"),
        ("transfer self account", "", "generic_expense", "unknown", "Others"),
        ("online payment general", "", "generic_expense", "unknown", "Others"),
        ("upi payment unknown", "", "generic_expense", "unknown", "Others"),
        ("credit card charges", "", "generic_expense", "unknown", "Others"),
        ("overdraft fee bank", "", "generic_expense", "unknown", "Others"),
        ("convenience fee charges", "", "generic_expense", "unknown", "Others"),
        ("stamp paper charges", "", "generic_expense", "unknown", "Others"),
        ("notary fee legal", "", "generic_expense", "unknown", "Others"),
        ("passport photo id card", "", "generic_expense", "unknown", "Others"),
        ("photocopy xerox print", "", "generic_expense", "unknown", "Others"),
        ("courier delivery charges", "", "generic_expense", "unknown", "Others"),
        ("tip gratuity service", "", "generic_expense", "unknown", "Others"),
        ("pet food animal care", "", "generic_expense", "unknown", "Others"),
        ("cleaning supplies home", "", "generic_expense", "unknown", "Others"),
        ("temple donation religious", "", "generic_expense", "unknown", "Others"),
        ("miscellaneous untracked", "", "generic_expense", "unknown", "Others"),
    ]

    features = []
    labels = []
    for title, merchant, intent, entity, category in data:
        feature_str = f"{title} {merchant} {intent} {entity}".lower().strip()
        features.append(feature_str)
        labels.append(category)

    return features, labels
